add deps, fix code
- added missing dependencies
- use sendmail as transport (minimum viable example)
- fixed some code errors (extra })

client size auth still does not work, errors with

```
info: after: users - Method: find
info: error: authManagement - Method: create: User not found.
error:  BadRequest: User not found.
    at BadRequest (`feathers-passwordless-auth-example/node_modules/feathers-errors/lib/index.js:93:17)
    at getUserData (feathers-passwordless-auth-example/node_modules/feathers-authentication-management/lib/helpers.js:93:11)
    at feathers-passwordless-auth-example/node_modules/feathers-authentication-management/lib/sendResetPwd.js:32:14
    at <anonymous>
```